### ISSUE TITLE
Cannot open sharp.node

### ISSUE THREAD

**Issue by kaisellgren** [smt116/node-native-ext-loader#10]
Amazing library, but I'm having difficulties using the npm sharp library:

```
Error:
Something went wrong installing the "sharp" module

Cannot open /home/nettisafka/dist/server/sharp.node: Error: Error loading shared library libvips-cpp.so.42: No such file or directory (needed by /home/nettisafka/dist/server/sharp.node)
```

I am building it with Webpack inside a Docker Alpine:

```js
        {
          test: /\.node$/,
          use: [
            {
              loader: 'native-ext-loader',
              options: {
                rewritePath: path.resolve(__dirname, 'dist/server'),
              },
            },
          ],
        },
```

It correctly copies the `sharp.node` and the compiled source code seems to point to the correct path:

![image](https://user-images.githubusercontent.com/148256/83299375-b776c200-a1fe-11ea-91b5-21ec11585e02.png)

I'm out of ideas. I'm pointing to the right path, I gave it 0777 permissions and the file is actually there. Any ideas what could be wrong?

**Comment by smt116** [comment]
It looks like you are building the package for a different target platform or you do not have dependencies of sharp on the target (e. g. https://github.com/lovell/sharp/issues/2218).

**Comment by kaisellgren** [comment]
So it's an issue with the installation, not the bundling. Thanks, I'll look into it.
