### ISSUE TITLE
how to write rule with webpack-chain

### ISSUE THREAD

**Issue by bjwulin** [smt116/node-native-ext-loader#12]
I write:
chainWebpack(config, { webpack }) {
    config.module.rule('trtc').test(/\.node$/).use('native-ext-loader').loader('native-ext-loader').options({ emit: false, rewritePath: process.env.NODE_ENV === 'production' ? './' : 'node_modules/trtc-electron-sdk/build/Release/' });
  },

but finally it is:
 test: /\.node$/,
        use: [
          {
            loader: 'native-ext-loader',
            options: {
              emit: false,
              rewritePath: 'node_modules/trtc-electron-sdk/build/Release/'
            }
          }
        ]
      }

and it should be:
{
        test: /\.node$/,
        loader: 'native-ext-loader',
        options: {
          emit: false,
          rewritePath:
            process.env.NODE_ENV === 'production'
              ? './'
              : 'node_modules/trtc-electron-sdk/build/Release/'
        }
      }

how to write webpack-chain rule?

**Comment by smt116** [comment]
I'm not familiar with the webpack-chain package, and I can't help with it. Please use issues to report bugs or features. For asking for help, you might want to use websites like https://stackoverflow.com.
