### ISSUE TITLE
Need example

### ISSUE THREAD

**Issue by Chrisigrimm** [smt116/node-native-ext-loader#6]
Hello there,

could someone please make an example electron app with a native module?
For development and production please.

Thanks and kind regards,
Keyjin

**Comment by amilajack** [comment]
https://github.com/amilajack/erb-sqlite-example/

**Comment by Chrisigrimm** [comment]
holy smoke that was a fast response. But you dont use native-ext-loader in your example.

**Comment by amilajack** [comment]
i think this should be closed now
