### ISSUE TITLE
How to load the module correctly?

### ISSUE THREAD

**Issue by martijnmichel** [smt116/node-native-ext-loader#9]
So im trying to package node-pty into my electron application. With this plugin the pty.node gets copied correctly into the root dir of my (quasar/vue) app.

However, how am I supposed to require/import the module into my app? When I keep using require('node-pty') nothing actually changed and i still get the same error when launching the built app that node-pty cannot be found.

You can see all source code + check out the error at releases here:
https://github.com/martijnmichel/nordvpn-linux

**Comment by smt116** [comment]
> When I keep using require('node-pty') nothing actually changed and i still get the same error when launching the built app that node-pty cannot be found.

I'm not familiar with the quasar, but I guess the application tries to find the extension in the wrong directory. Take a look at [`basePath` configuration option](https://github.com/smt116/node-native-ext-loader#basepath-default-). The easiest way to debug it would be to build the application and check where the extension has been copied and where [it suppose to be placed](https://github.com/smt116/node-native-ext-loader/blob/master/index.js#L46-L47).

**Comment by martijnmichel** [comment]
somehow I found out I could add "node-pty": "commonjs node-pty" to webpacks externals and thus i didnt need this library. Although i dont fully know why it does work now, it does ;)

**Comment by martijnmichel** [comment]
I found out that my linux snap build doesnt work yet (whereas appimage works fine) It says node-pty cant be found.

![Screenshot_20200419_123129](https://user-images.githubusercontent.com/38880192/79685549-e847fc80-8239-11ea-8b0b-8bd975849b52.png)

If i use this plugin i do see pty.node file coming up in the root of the package, how can i include it for dev and build? because im not sure it outputs the file on dev aswell...?

**Comment by smt116** [comment]
> because im not sure it outputs the file on dev aswell...?

You can check in the build directory ;). It will emit the file if it has been enabled in the configuration (it is by default) and if the `emitFile` function exists (see https://github.com/smt116/node-native-ext-loader/blob/master/index.js#L13-L19). You should be able to include it just like other packages. The path where the file is copied may depend on your build process, but you can always adjust it using `basePath` configuration option.

I'm not familiar with the quasar, but if you think this does not work as expected, I can take a look in the following days (tomorrow or the day after).

**Comment by martijnmichel** [comment]
actually i am very confused whether this is what i need because the app doesnt even work if i require('somepath/pty.node') because of some error, what i need is require('node-pty') as a whole module.. but i need to include it in my electron app. Its not quasar related. Do you know if this is the right way to ship node-pty in the app ?

**Comment by smt116** [comment]
I've built your app locally and it works fine. The problem seems to exist only in development so it needs to be a configuration-relevant issue.

**Comment by martijnmichel** [comment]
Hey! Thanks for taking the time to help me.

I am not sure what you mean it works fine? What does? Did you import pty.node from basePath folder on development process and production?

The issue im experiencing is with distributing the app when built. The snap file (and before also the appimage file) cant find the pty.node in package node-pty.

**Comment by smt116** [comment]
I meant that I've built the app for production and opened the dmg file. Then, I've clicked on the "terminal" button and I was able to run commands.

**Comment by martijnmichel** [comment]
well yes thats because it will build the package for your system, but noone else can run it. I can run my own builds perfectly fine but when i let someone else try they wont find node-pty :(

**Comment by smt116** [comment]
Oh. I didn't get that the problem is when running on another computer. Is it exactly the same platform? I've used Webpack and electron-builder in one project and I had to build for each platform independently (including installing dependencies). Something like:

```
yarn run electron-builder install-app-deps --platform win32 --arch x64
TARGET=release BUILD_TS=true BUILD_ELM=true yarn run webpack
yarn run electron-builder build --windows --x64
```

You are using quasar so you need to ensure it installs or compiles native extension for the target system. Also, you may be missing some configuration for bundling native extension into the package, e. g. for Webpack would be something like:

```
const mainProcessConfig = {
  target: 'electron-main',
  entry: {
    index: './src/main/index.ts'
  },
  node: {
    __dirname: false
  },
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: '[name].js'
  },
  module: {
    rules: [
      # ...
      {
        test: /\.node$/,
        loader: 'native-ext-loader'
      }
    ]
  },
  # ...
}
```
